apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: your-certificate-name
  namespace: your-namespace
spec:
  secretName: your-secret-name
  issuerRef:
    name: your-issuer-name
    kind: ClusterIssuer  # Use 'Issuer' for a namespace-specific issuer
  dnsNames:
    - yourdomain.com  # Replace with your actual domain
  acme:
    config:
      - http01:
          ingressClass: nginx  # Use the appropriate ingress class
        domains:
          - yourdomain.com  # Replace with your actual domain