apiVersion: controller.kubeslice.io/v1alpha1
kind: SliceConfig
metadata:
 name: yello
 namespace: kubeslice-avesha
spec:
 sliceSubnet: 10.32.0.0/16
 sliceType: Application
 sliceGatewayProvider:
   sliceGatewayType: OpenVPN
   sliceCaType: Local
 sliceIpamType: Local
 clusters:
   - worker1-cluster
   - worker2-cluster
 qosProfileDetails:
   queueType: HTB
   priority: 1
   tcType: BANDWIDTH_CONTROL
   bandwidthCeilingKbps: 5120
   bandwidthGuaranteedKbps: 2560
   dscpClass: AF11
 namespaceIsolationProfile:
   applicationNamespaces:
    # - namespace: iperf
    #   clusters:
    #   - '*'
